#!/bin/bash
HOOK_NAMES="pre-commit"
# assuming the script is in a bin directory, one level into the repo
HOOK_DIR=$(git rev-parse --show-toplevel)/.git/hooks
# directory with codestyle files
CODESTYLE_DIR=$(git rev-parse --show-toplevel)/codestyle


for hook in $HOOK_NAMES; do
    # If the hook already exists, is executable, and is not a symlink
    if [ ! -h $HOOK_DIR/$hook -a -x $HOOK_DIR/$hook ]; then
        mv $HOOK_DIR/$hook $HOOK_DIR/$hook.local
    fi
    # create a symlink
    ln -s -f $CODESTYLE_DIR/$hook $HOOK_DIR/$hook
done
