#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

PROJECT_PATH="."

CODESTYLE_PATH="$PROJECT_PATH/codestyle"

# Astyle part

echo -e "\033[32;1;40mAstyle processing \033[0m"

ASTYLE_CONF="$CODESTYLE_PATH/astyle.conf"

if ! [ -f $ASTYLE_CONF ]
then
	echo "No astyle conf"
else
    astyle --options=$ASTYLE_CONF "*.cpp" "*.h"
fi

# Remove trailing spaces
echo -e "\033[32;1;40mSED processing: removing trailing spaces \033[0m"
find $PROJECT_PATH -regex ".*\(cpp\|h\)$" -type f -print0 | xargs -0 sed -i 's/[[:space:]]*$//'

echo -e "\033[32;1;40mCpplint.py processing: make warnings \033[0m"

# Check with cpplint
CPPLINT_LOG="$CODESTYLE_PATH/cpplint.stderr"

if ! sh -c "python $CODESTYLE_PATH/cpplint.py \
        --root=$PROJECT_PATH/ \
        --linelength=120 \
        --exclude=CMakeFiles \
        --recursive \
        --headers=h \
        --extensions=cpp \
        $PROJECT_PATH/*" 2> $CPPLINT_LOG
then
    echo "Codestyle check failed. See report:"
    cat $CPPLINT_LOG
    rm -f $CPPLINT_LOG
    exit 1
else
    echo "Codestyle check succeed"
    exit 0
fi

rm -f $CPPLINT_LOG




if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
    # Note that the use of brackets around a tr range is ok here, (it's
    # even required, for portability to Solaris 10's /usr/bin/tr), since
    # the square bracket bytes happen to fall in the designated range.
    test $(git diff --cached --name-only --diff-filter=A -z $against |
      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
    cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
    exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
